# ---------------------------------------------------------
# Nombre del proyecto
# ---------------------------------------------------------
spring.application.name=levelupbackend

# ---------------------------------------------------------
# Configuración de la base de datos PostgreSQL
# ---------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/levelup_database
spring.datasource.username=postgres
spring.datasource.password=pass1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------------------------------------------------
# Configuración de JPA / Hibernate
# ---------------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------------------------------------------------------
# Prefijo para todas las rutas del backend
# ---------------------------------------------------------
server.servlet.context-path=/api
