# ---------------------------------------------------------
# Nombre del proyecto
# ---------------------------------------------------------
spring.application.name=levelupbackend

# ---------------------------------------------------------
# Configuración de la base de datos PostgreSQL
# ---------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/levelup_db
spring.datasource.username=postgres
spring.datasource.password=pass1234

# ---------------------------------------------------------
# Configuración de JPA
# ---------------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------------------------------------------------------
# Prefijo para todas las rutas del backend
# Ejemplo:
#   /api/auth/login
#   /api/productos
#   /api/carrito
# ---------------------------------------------------------
server.servlet.context-path=/api
